use 5.018001;
use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    NAME              => 'Route4MeSDK',
    VERSION_FROM      => 'lib/Route4MeSDK.pm', # finds $VERSION, requires EU::MM from perl >= 5.5
    PREREQ_PM         => { 'HTTP::Tiny' => 0.025, 'JSON' => 2.9, 'Data::Dumper' => 2.145, 'URI' => 1.64, 'URI::QueryParam' => 1.64, 'Moose' => 2.1206, 'Moose::Util::TypeConstraints' => 2.1206}, # e.g., Module::Name => 1.1
    ABSTRACT_FROM     => 'lib/Route4MeSDK.pm', # retrieve abstract from module
    AUTHOR            => 'A. U. Thor <a.u.thor@a.galaxy.far.far.away>',
    #LICENSE           => 'perl',
    #Value must be from legacy list of licenses here
    #http://search.cpan.org/perldoc?Module%3A%3ABuild%3A%3AAPI
);
